favicon: /img/logo/icon.jpg
banner: /images/webstack_banner_cn.png

logo:
  expanded: /img/logo/å„ç§å°ºå¯¸/48.png
  collapsed: /img/logo/å„ç§å°ºå¯¸/48.png
  dark: /img/logo/å„ç§å°ºå¯¸/48.png

flag:
  - name: Chinese
    default: true
    icon: flag-cn
    index: /index.html

search: true

userDefinedSearchData:
  custom: false
  thisSearch: https://www.baidu.com/s?wd=
  thisSearchIcon: url(https://www.baidu.com/favicon.ico)
  hotStatus: true
  data:
    - name: ç™¾åº¦
      img: url(https://www.baidu.com/favicon.ico)
      url: https://www.baidu.com/s?wd=
    - name: è°·æ­Œ
      img: url(https://www.google.com/favicon.ico)
      url: https://www.google.com/search?q=

githubCorner: '<a href="https://github.com/HCLonely/hexo-theme-webstack" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

since: 2024

expandAll: false
menu:
  - name: å…³äºæˆ‘çš„
    icon: far fa-star
    config: my

  - name: å­¦æ ¡äº‹åŠ¡
    icon: fa fa-graduation-cap
    config: qfnu

  - name: ä¸»é¢˜é­”æ”¹
    icon: fa fa-edit
    config: theme

  - name: å¸¸ç”¨å·¥å…·
    icon: far fa-star
    config: hotTools

  - name: å…¶ä»–å·¥å…·
    icon: fas fa-tools
    submenu:
      - name: å¼€å‘å·¥å…·
        icon: fas fa-tools
        config: devTools
      - name: æˆ‘çš„åšå®¢
        icon: fas fa-blog
        config: myBlog

#############å…³äºæˆ‘çš„####################################################################################################
my:
  - name: æˆ‘çš„ä¸»é¡µ
    url: https://w1ndys.top
    img: https://blog.w1ndys.top/img/logo/700/whiten.png
    description: è¿™æ˜¯æˆ‘çš„ä¸ªäººä¸»é¡µ

  - name: æˆ‘çš„åšå®¢
    url: https://blog.w1ndys.top
    img: https://blog.w1ndys.top/img/logo/700/whiten.png
    description: è¿™æ˜¯æˆ‘çš„ä¸ªäººåšå®¢

  - name: æ›²é˜œå¸ˆèŒƒå¤§å­¦é€‰è¯¾æŒ‡åŒ—
    url: https://xkzb.qfnu.w1ndys.top
    img: https://blog.w1ndys.top/img/logo/700/whiten.png
    description: ä¸€ä¸ªå…è´¹çš„å…¬ç›Šé¡¹ç›®

  - name: æ›²é˜œå¸ˆèŒƒå¤§å­¦é€Ÿé€šæŒ‡å—
    url: https://stzn.qfnu.w1ndys.top
    img: https://blog.w1ndys.top/img/logo/700/whiten.png
    description: å¦ä¸€ä¸ªå…è´¹çš„å…¬ç›Šé¡¹ç›®

#############å­¦æ ¡äº‹åŠ¡####################################################################################################
qfnu:
  - name: Uæ ¡å›­/Welearn/æ™ºæ…§æ ‘/é›¨è¯¾å ‚/å­¦ä¹ é€š/é—®å·æ˜Ÿ/è…¾è®¯é—®å·ç­‰196å¹³å°è‡ªåŠ¨ç­”é¢˜é€šæ€è„šæœ¬
    url: https://blog.w1ndys.top/posts/1ff200e1
    img: https://blog.w1ndys.top/img/about/avatar.png
    description: é€šæ€è„šæœ¬å®‰è£…æ•™ç¨‹

  - name: æ›²é˜œå¸ˆèŒƒå¤§å­¦
    url: https://www.qfnu.edu.cn/#/
    img: https://q1.qlogo.cn/g?b=qq&nk=1623557647&s=640#/
    description: æ›²é˜œå¸ˆèŒƒå¤§å­¦å®˜ç½‘

  - name: æ›²é˜œå¸ˆèŒƒå¤§å­¦ç½‘ç»œç©ºé—´å®‰å…¨å­¦é™¢
    url: https://cyber.qfnu.edu.cn/
    img: https://q1.qlogo.cn/g?b=qq&nk=3309083558&s=640#/
    description: æ›²é˜œå¸ˆèŒƒå¤§å­¦ç½‘ç»œç©ºé—´å®‰å…¨å­¦é™¢å®˜ç½‘

  - name: æ›²é˜œå¸ˆèŒƒå¤§å­¦å›¾ä¹¦é¦†é¢„çº¦ç³»ç»Ÿ
    url: http://libyy.qfnu.edu.cn/
    img: /img/ico/lib.ico
    description: ä¸Šè‡ªä¹ ç¥å™¨å•Š

  - name: çŸ¥æ–°æ•™è‚²å­¦ç”Ÿç«¯
    url: https://stu.z-xin.net/
    img: /img/ico/zx.png
    description: ç½‘ç»œç©ºé—´å®‰å…¨å­¦é™¢æ•°å­—å¤§è„‘å›¢é˜Ÿå¼€å‘ï¼Œå¼ºğŸ‘

  - name: æ›²é˜œå¸ˆèŒƒå¤§å­¦æ•™åŠ¡ç³»ç»Ÿ
    url: http://zhjw.qfnu.edu.cn/
    img: https://q1.qlogo.cn/g?b=qq&nk=1623557647&s=640#/
    description: æ›²é˜œå¸ˆèŒƒå¤§å­¦æ•™åŠ¡ç³»ç»Ÿç™»é™†å…¥å£

  - name: FIFå£è¯­è®­ç»ƒå¹³å°
    url: https://www.fifedu.com/iplat/html/index.html
    img: https://tse1-mm.cn.bing.net/th/id/OIP-C.vclTk2wE3zp3riNabHxVeAHaHa?rs=1&pid=ImgDetMain
    description: å¤§å­¦ç”Ÿså› ä¹‹ä¸€

  - name: iWriteå†™ä½œç³»ç»Ÿ
    url: https://iwrite.unipus.cn/login#/
    img: https://ts1.cn.mm.bing.net/th/id/R-C.29b7c637d0e32c2251b15e492fba7cb9?rik=AprJLuudx1%2b%2feg&riu=http%3a%2f%2fimg.mp.itc.cn%2fupload%2f20170703%2f64ba7dee4d2845bc8682b9f601e12c7e_th.jpg&ehk=xlUcy2FYNa%2bDw63l1zYBhbUD62ftqv4YDC7a%2feBSxlg%3d&risl=&pid=ImgRaw&r=0
    description: å¤§å­¦ç”Ÿså› ä¹‹ä¸€

  - name: Uæ ¡å›­
    url: https://u.unipus.cn/
    img: https://img.onlinedown.net/download/202010/132516-5f8145bc966b7.jpg
    description: å¤§å­¦ç”Ÿså› ä¹‹ä¸€

  - name: Welearnéšè¡Œè¯¾å ‚
    url: https://welearn.sflep.com/#/
    img: https://ts1.cn.mm.bing.net/th/id/R-C.bf7a8f2a92df7e65f2d7218208626a99?rik=PFFBIYxqJNq%2fqw&riu=http%3a%2f%2fimg.kxdw.com%2f2021%2f0802%2f20210802050832841.png&ehk=5Od1t%2fQrzpTCv2LR%2brDSzThBRx34QFRJtFwTKY88Lzs%3d&risl=&pid=ImgRaw&r=0
    description: å¤§å­¦ç”Ÿså› ä¹‹ä¸€

  - name: é•¿æ±Ÿé›¨è¯¾å ‚
    url: https://changjiang.yuketang.cn/web#/
    img: https://ts1.cn.mm.bing.net/th?id=OIP-C.SdEkfsLqEiuiid9hIDgSOQAAAA&w=120&h=120&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2#/
    description: å¤§å­¦ç”Ÿså› ä¹‹ä¸€

  - name: æ™ºæ…§æ ‘ç½‘|çŸ¥åˆ°
    url: https://www.zhihuishu.com/
    img: https://img.onlinedown.net/new_tag/202012/807.jpg
    description: åˆ·å­”è®ºå’Œåœ¨çº¿è¯¾çš„

  - name: æ™ºæ…§æ ‘ç½‘|çŸ¥åˆ°åˆ·è¯¾è„šæœ¬
    url: https://blog.w1ndys.top/posts/1ff200e1
    img: https://img.onlinedown.net/new_tag/202012/807.jpg
    description: å…¶å®æˆ‘å°±æ˜¯å¤©å…‹å‰è¾¹é‚£ä½ç½‘ç«™

  - name: è¶…æ˜Ÿå­¦ä¹ é€šç™»é™†å…¥å£
    url: https://passport2.chaoxing.com/login/#/
    img: https://tse1-mm.cn.bing.net/th/id/OIP-C.8_75aRovTdF0Zc3W04GpUQHaHa?rs=1&pid=ImgDetMain
    description: å¤§å­¦ç”Ÿè‡´æ­»è½¯ä»¶

  - name: å­¦ä¹ é€šåˆ·è¯¾è„šæœ¬
    url: https://blog.w1ndys.top/posts/1ff200e1
    img: https://tse1-mm.cn.bing.net/th/id/OIP-C.8_75aRovTdF0Zc3W04GpUQHaHa?rs=1&pid=ImgDetMain
    description: å¤§å­¦ç”Ÿæ•‘æ´»è„šæœ¬ï¼Œå¤©å…‹å‰é¢é‚£ä½

  - name: PubScholarå…¬ç›Šå­¦æœ¯å¹³å°
    url: https://pubscholar.cn/
    img: https://tse1-mm.cn.bing.net/th/id/OIP-C.Gc0kFd2q83ymwBIqNKThXgHaHa?rs=1&pid=ImgDetMain
    description: æ¯”çŸ¥ç½‘è‰¯å¿ƒ

  - name: ä¸­å›½æ•™è‚²å¹²éƒ¨ç½‘ç»œå­¦é™¢
    url: https://study.enaea.edu.cn/login.do#/
    img: https://tse4-mm.cn.bing.net/th/id/OIP-C.xMuFA-fQpLDeBXfdZgv5wAAAAA?rs=1&pid=ImgDetMain
    description: æ”¿æ²»æ•™è‚²ç³»åˆ—ï¼Œçˆ±å…šçˆ±äººæ°‘

  - name: ChatGPT
    url: https://chat.openai.com/
    img: https://ts1.cn.mm.bing.net/th/id/R-C.44f7b44e144c3e62a7bf26d3ed9dbc25?rik=4mNHzi4yH%2fL%2bGQ&riu=http%3a%2f%2fwww.kuaipng.com%2fUploads%2fpic%2fw%2f2023%2f02-09%2f135403%2fwater_135403_698_698_.png&ehk=D%2bT8GsjcmjFS9uaNJ2JvSOP8R8kbzcmFHLdm8GV69lU%3d&risl=&pid=ImgRaw&r=0
    description: å¤§å­¦ç”Ÿçš„å¥½å¸®æ‰‹ï¼Œä½†ä¹Ÿè¦æ³¨æ„ä¸è¦æ»¥ç”¨å“¦~

  # - name:
  #   url:
  #   img:
  #   description:

#############ä¸»é¢˜é­”æ”¹####################################################################################################
theme:
  - name: å®‰çŸ¥é±¼çš„åšå®¢
    url: https://blog.anheyu.com/#/
    img: https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg#/
    description: å¾ˆå‰å®³çš„é­”æ”¹åšä¸»

  - name: çŒªæ¢¨æ‘çš„åšå®¢
    url: https://zoulicheng.cn/posts/aa661f41.html#/
    img: https://zoulicheng.oss-cn-shanghai.aliyuncs.com/img/quin.jpg
    description: å­¦ä¹ ä¸€ä¸‹å¤§ä½¬çš„é­”æ”¹ç¾åŒ–

  - name: FomalhautğŸ¥
    url: https://www.fomal.cc/categories/%E9%AD%94%E6%94%B9%E6%95%99%E7%A8%8B/#/
    img: https://sourcebucket.s3.bitiful.net/img/avatar.webp
    description: Future is now ğŸ­ğŸ­ğŸ­

  - name:
    url:
    img:
    description:
  - name:
    url:
    img:
    description:
  - name:
    url:
    img:
    description:
  - name:
    url:
    img:
    description:

#############å¼€å‘å·¥å…·####################################################################################################

devTools:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: é¢å‘å¼€æºåŠç§æœ‰è½¯ä»¶é¡¹ç›®çš„æ‰˜ç®¡å¹³å°ã€‚
  - name: CSDN
    url: https://www.csdn.net/
    img: /img/ico/CSDN.ico
    description: ä¸“ä¸šå¼€å‘è€…ç¤¾åŒº

#############æˆ‘çš„åšå®¢####################################################################################################

myBlog:
  - name: æˆ‘çš„åšå®¢
    url: https://blog.w1ndys.top
    img: https://blog.w1ndys.top/img/logo/700/whiten.png
    description: è¿™æ˜¯æˆ‘çš„ä¸ªäººåšå®¢

about:
  url: /about/
  icon: far fa-heart
  name: å…³äºæœ¬ç«™

#############å…³äºé¡µé¢####################################################################################################

aboutPage:
  website:
    head: å…³äºæœ¬ç«™
    html: '<blockquote><p>æœ¬ç«™æ˜¯ç”±hexoä¸»é¢˜<a href="https://github.com/HCLonely/hexo-theme-webstack">hexo-theme-webstack</a>å¼ºåŠ›é©±åŠ¨çš„W1ndysè‡ªå»ºå¯¼èˆªç«™ï¼Œæ—¨åœ¨æ”¶å½•å¸¸ç”¨ç½‘ç«™ï¼Œä¾¿äºæ—¥å¸¸å­¦ä¹ ç­‰çš„ä½¿ç”¨ã€‚</p></blockquote>'
  webmaster:
    head: å…³äºç«™é•¿
    name: W1ndys
    url: https://blog.w1ndys.top/
    img: https://blog.w1ndys.top/img/logo/700/whiten.png
    description: æ¬²æˆ´çš‡å† ï¼Œå¿…æ‰¿å…¶é‡
    html: ""

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: æœ¬ç«™æ€»è®¿é—®é‡$pv
  uv: æœ¬ç«™æ€»è®¿å®¢æ•°$uv

custom:
  head:
    |- # ä»¥ä¸‹å†…å®¹æ’å…¥åˆ°<head></head>æ ‡ç­¾å†…ï¼Œå¯è®¾ç½®å¤šè¡Œï¼Œæ³¨æ„æ¯è¡Œå¼€å¤´è‡³å°‘å››ä¸ªç©ºæ ¼
    <!-- ç›´æ¥æ·»åŠ htmlå†…å®¹å³å¯ -->
    <!-- å¯è®¾ç½®å¤šè¡Œ -->
  body: |- # ä»¥ä¸‹å†…å®¹æ’å…¥åˆ°</body>æ ‡ç­¾ä¹‹å‰ï¼Œå¯è®¾ç½®å¤šè¡Œï¼Œæ³¨æ„æ¯è¡Œå¼€å¤´è‡³å°‘å››ä¸ªç©ºæ ¼
    <!-- ç›´æ¥æ·»åŠ htmlå†…å®¹å³å¯ -->
    <!-- å¯è®¾ç½®å¤šè¡Œ -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
